[workspace]
members = [
	"crates/libedgedns", 
	"crates/server",
	"crates/sandbox/guest",
]
exclude = [
	"tests",
]

[profile.release]
lto = true
debug = true

[profile.bench]
debug = true
panic = 'abort'

[profile.test]
debug = true
