version: '3'
services:
  nginx: 
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
      - 8443:443
      - 8853:853
  edgedns:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./:/app:ro
    command: /usr/local/cargo/bin/edgedns -c /app/edgedns.toml
    environment:
      - RUST_LOG=info
    expose:
      - "9090"
      - "53"
    ports:
      - "8053:53"
