[package]
name = "guest"
version = "0.1.0"
authors = ["Marek Vavruša <mvavrusa@cloudflare.com>"]
edition = "2018"

[features]
default = ["futures"]
futures = ["futures-preview/std"]

[dependencies]
futures-preview = { version = "=0.3.0-alpha.13", default-features = false, optional = true }