[package]
name = "libedgedns"
version = "0.4.0"
authors = ["Frank Denis <github@pureftpd.org>", "Marek Vavrusa <marek@vavrusa.com>"]
publish = false
edition = "2018"

[lib]
name = "libedgedns"
path = "src/lib.rs"

[dependencies]
clippy = {version = "*", optional = true}
failure = "*"
failure_derive = "*"
futures = "*"
lazy_static = "*"
log = "*"
coarsetime = "*"
rand = "^0.6"
toml = "*"
bytes = "*"
jumphash = {git = "https://github.com/jedisct1/rust-jumphash"}
tokio = {git = "https://github.com/tokio-rs/tokio", features=["async-await-preview"]}
domain-core = {git = "https://github.com/vavrusa/domain-core"}
kres = {git = "https://github.com/vavrusa/rust-kres", features=["static"]}
parking_lot = {version = "0.6", features = ["nightly"]}
clockpro-cache = {git = "https://github.com/jedisct1/rust-clockpro-cache"}
prometheus = "*"
hex = "0.3"
socket2 = {version = "0.3", features = ["reuseport"]}